include:
  - local: '.gitlab-ci-template.yml'

variables:
  DB_MIGRATE: python manage.py migrate && python manage.py init_bootstrap
  CI_DEBUG_TRACE: 0
  DOCKER_IMAGE_NAME: "ci-configuration-test"

build:
  extends: .build

build-singlestage:
  extends: .build
  variables:
    DOCKER_BUILD_SOURCE: "Singlestage-Dockerfile"
    DOCKER_IMAGE_NAME: "ci-configuration-test-singlestage"

review-mysql:
  extends: review
  variables:
    MYSQL_ENABLED: 1

test:
  extends: .test

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.anders.fi/".insteadOf "git@git.anders.fi:"
  - mkdir -p /tmp/devops/ci-configuration && cp -rf ./* /tmp/devops/ci-configuration/.
  - git clone --single-branch --branch master git@git.anders.fi:anders/ci-configuration-test.git /tmp/devops/ci-configuration-test
  - cd /tmp/devops/ci-configuration-test/
  - source /tmp/devops/ci-configuration/auto-devops.sh
