image: docker.anders.fi/anders/ci-configuration:python-refactor-build-image

stages:
  - build
  - test
  - review
  - staging
  - cleanup_review

variables:
  DOCKER_BUILD_CONTEXT: "."

  # Docker by default users `vfs` which is not suitable for
  # production use. overlay2 is the preferred driver by Docker.
  DOCKER_DRIVER: overlay2

  # If the host is not set docker cli will try to use a 172.x.x.x
  # IP when connecting to the Docker API, which will not work
  DOCKER_HOST: "tcp://localhost:2375"

  # Default usernames and passwords for postgres setups
  # Note: These are the credentials that will be used for testing
  DATABASE_USER: user
  DATABASE_PASSWORD: testing-password

  # Which version of Postgres that will be installed for testing
  # and for preview environments
  POSTGRES_VERSION_TAG: "9.6"

  # Which version of MySQL should be used if enabled
  MYSQL_VERSION_TAG: "5.7"

  # Default name for the database
  DATABASE_DB: "$CI_ENVIRONMENT_SLUG"

.build:
  services:
    - docker:stable-dind
  variables:
    DOCKER_BUILD_SOURCE: Dockerfile
  stage: build
  script:
    - devops create_images
  only:
    - merge_requests
    - master
    - qa
  except:
    variables:
      - $BUILD_DISABLED

.test:
  services:
    - docker:stable-dind
  stage: test
  script:
    - set_env_from_devops docker_test_image BUILT_DOCKER_TEST_IMAGE
    - devops test_setup
    - make test
  only:
    - merge_requests
    - master
    - qa
  except:
    variables:
      - $TEST_DISABLED

.light-test:
  stage: test
  tags:
    - light
  only:
    - merge_requests
    - master
    - qa
  except:
    variables:
      - $TEST_DISABLED

.review:
  stage: review
  script:
    - devops deploy_application --track review
  environment:
    name: qa/r/${CI_COMMIT_REF_SLUG}
    url: http://$CI_PROJECT_PATH_SLUG-$CI_ENVIRONMENT_SLUG.$K8S_QA_INGRESS_DOMAIN
    on_stop: stop_review
  variables:
    POSTGRES_ENABLED: 1
  only:
    refs:
      - merge_requests
    kubernetes: active
  except:
    refs:
      - master
    variables:
      - $REVIEW_DISABLED

.review-cleanup:
  variables:
    git_strategy: none
  environment:
    name: qa/r/${CI_COMMIT_REF_SLUG}
    action: stop
  stage: cleanup_review
  script:
    - devops review_cleanup
  only:
    refs:
      - merge_requests
    kubernetes: active
  except:
    refs:
      - master
    variables:
      - $REVIEW_DISABLED

.cleanup_review:
  extends: .review-cleanup
  allow_failure: false
  when: on_failure

.stop_review:
  extends: .review-cleanup
  allow_failure: true
  when: manual

.staging:
  stage: staging
  script:
    - devops deploy_application --track staging
  environment:
    name: qa/staging
    url: http://$CI_PROJECT_PATH_SLUG-qa.$K8S_QA_INGRESS_DOMAIN
  variables:
    POSTGRES_ENABLED: 0
  only:
    refs:
      - master
    kubernetes: active
  except:
    variables:
      - $STAGING_DISABLED

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.anders.fi/".insteadOf "git@git.anders.fi:"
  - git clone --single-branch --branch v2-testing git@git.anders.fi:anders/ci-configuration.git /tmp/devops/ci-configuration
  - export PATH="$PATH:/tmp/devops/ci-configuration"
  - source /tmp/devops/ci-configuration/utils/set_env_from_devops.sh
