include:
  - local: '.gitlab-ci-base-template.yml'

variables:
  DEVELOPMENT_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-development
  KOLGA_BRANCH: ${CI_COMMIT_REF_NAME}

stages:
  - build
  - test
  - post-test
  - release

.code-tests:
  image: ${DEVELOPMENT_IMAGE}
  tags:
    - light
  only:
    - merge_requests
    - master
    - v3

build:
  extends: .build
  only:
    - merge_requests
    - master
    - /^r-[\d]+$/
    - v3

test-image:
  extends: .docker-image-scan
  allow_failure: true

sonar:
  extends: .sonar
  needs: ["test","test-sast"]
  dependencies:
    - test
    - test-sast
  allow_failure: true

pages:
  stage: release
  image: ${DEVELOPMENT_IMAGE}
  script:
    - make docs
    - mv -vi docs/_build/html public/
  only:
    - v3
  artifacts:
    paths:
      - public

release-local:
  stage: release
  extends: .build
  only:
    - v3

release-dockerhub:
  stage: release
  extends: .build
  variables:
    CONTAINER_REGISTRY: index.docker.io
    CONTAINER_REGISTRY_USER: ${DOCKERHUB_REGISTRY_USER}
    CONTAINER_REGISTRY_PASSWORD: ${DOCKERHUB_REGISTRY_PASSWORD}
    CONTAINER_REGISTRY_REPO: andersinnovations/devops
  only:
    - v2

test-style:
  extends: .code-tests
  script:
    - make style-tests

test-typing:
  extends: .code-tests
  script:
    - make typing-tests

test-packages:
  extends: .code-tests
  script:
    - make package-tests

test-docs:
  extends: .code-tests
  script:
    - make docs
  artifacts:
    paths:
      - docs/_build
    expire_in: 1 week

test-sast:
  extends: .code-tests
  script:
    - make sast-tests
  artifacts:
    paths:
      - bandit_report.json
    expire_in: 5 mins

test:
  extends: .test
  variables:
    CLIENT_COMMAND: pytest -ra -vvv --cov=. --cov-report xml --cov-report term --junit-xml=pytest.xml
  artifacts:
    paths:
      - pytest.xml
      - coverage.xml
    expire_in: 5 mins
  only:
    - merge_requests
    - v3

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.anders.fi/".insteadOf "git@git.anders.fi:"
  - export PATH="$PATH:$PWD"
  - source utils/shell_utils.sh
  - set_docker_host
  - echo 127.0.0.1 docker-registry >> /etc/hosts
