image: docker.anders.fi/anders/ci-runner-images/ci-runner:latest

stages:
  - build
  - test
  - review
  - staging
  - cleanup_review
  - stop_review

variables:
  DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME"

  # Docker by default users `vfs` which is not suitable for
  # production use. overlay2 is the preferred driver by Docker.
  DOCKER_DRIVER: overlay2

  # If the host is not set docker cli will try to use a 172.x.x.x
  # IP when connecting to the Docker API, which will not work
  DOCKER_HOST: "tcp://localhost:2375"

  # Default usernames and passwords for postgres setups
  # Note: These are the credentials that will be used for testing
  POSTGRES_USER: user
  POSTGRES_PASSWORD: testing-password

  # Which version of Postgres that will be installed for testing
  # and for preview environments
  POSTGRES_VERSION_TAG: "9.6"

  # Default name for the Postgres database
  POSTGRES_DB: "$CI_ENVIRONMENT_SLUG"

.build:
  image: docker.anders.fi/anders/ci-runner-images/ci-runner-docker:latest
  services:
    - docker:stable-dind
  variables:
    DOCKER_BUILD_SOURCE: Dockerfile
  stage: build
  script:
    - build
  except:
    variables:
      - $BUILD_DISABLED

.test:
  image: docker.anders.fi/anders/ci-runner-images/ci-runner-docker:latest
  services:
    - docker:stable-dind
  stage: test
  script:
    - test
  except:
    variables:
      - $TEST_DISABLED

review:
  stage: review
  script:
    - export
    - kube_auth qa
    - ensure_namespace
    - deploy
  environment:
    name: qa/r/${CI_COMMIT_REF_SLUG}
    url: http://$CI_PROJECT_PATH_SLUG-$CI_ENVIRONMENT_SLUG.$K8S_QA_INGRESS_DOMAIN
    on_stop: stop_review
  variables:
    POSTGRES_ENABLED: 1
  only:
    refs:
      - merge_requests
    kubernetes: active
  except:
    refs:
      - master
    variables:
      - $REVIEW_DISABLED

cleanup_review:
  stage: cleanup_review
  script:
    - kube_auth qa
    - delete
  when: on_failure
  only:
    refs:
      - merge_requests
    kubernetes: active
  except:
    refs:
      - master
    variables:
      - $REVIEW_DISABLED

stop_review:
  variables:
    git_strategy: none
  environment:
    name: qa/r/${CI_COMMIT_REF_SLUG}
    action: stop
  stage: stop_review
  script:
    - kube_auth qa
    - delete
  when: manual
  allow_failure: true
  only:
    refs:
      - merge_requests
    kubernetes: active
  except:
    refs:
      - master
    variables:
      - $REVIEW_DISABLED

staging:
  stage: staging
  script:
    - kube_auth qa
    - ensure_namespace
    - setup_helm
    - create_application_secret
    - deploy
  environment:
    name: qa/staging
    url: http://$CI_PROJECT_PATH_SLUG-qa.$K8S_QA_INGRESS_DOMAIN
  variables:
    POSTGRES_ENABLED: 1
  only:
    refs:
      - master
    kubernetes: active
  except:
    variables:
      - $STAGING_DISABLED

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.anders.fi/".insteadOf "git@git.anders.fi:"
  - git clone --single-branch --branch v0 git@git.anders.fi:anders/ci-configuration.git /tmp/devops/ci-configuration
  - source /tmp/devops/ci-configuration/auto-devops.sh
