include:
  - local: '.gitlab-ci-template.yml'

variables:
  DB_MIGRATE: python manage.py migrate && python manage.py init_bootstrap
  CI_DEBUG_TRACE: 0

build:
  extends: .build

test:
  extends: .test

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.anders.fi/".insteadOf "git@git.anders.fi:"
  - source ./auto-devops.sh
  - git clone --single-branch --branch master git@git.anders.fi:anders/ci-setup-test.git /tmp/ci-setup-test
  - cp -rf /tmp/ci-setup-test/* ./.
