include:
  - local: '.gitlab-ci-base-template.yml'

variables:
  SHA_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  DEVELOPMENT_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-development
  FINAL_IMAGE: ${CI_REGISTRY_IMAGE}:latest

stages:
  - build
  - test
  - release

.code-tests:
  image: ${DEVELOPMENT_IMAGE}
  only:
    - merge_requests
    - master
    - qa

build-image:
  extends: .build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - set +e && docker pull "${FINAL_IMAGE}" 2>/dev/null && set -e
    - docker build -t "${SHA_IMAGE}" .
    - docker build --target development -t "${DEVELOPMENT_IMAGE}" .
    - docker push "${SHA_IMAGE}"
    - docker push "${DEVELOPMENT_IMAGE}"

release:
  stage: release
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull "${SHA_IMAGE}"
    - docker tag ${SHA_IMAGE} ${FINAL_IMAGE}
    - docker push ${FINAL_IMAGE}
  only:
    - master

test-style:
  extends: .code-tests
  script:
    - make style-tests

test-typing:
  extends: .code-tests
  script:
    - make typing-tests

test-packages:
  extends: .code-tests
  script:
    - make packages-tests

test:
  extends: .test

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.anders.fi/".insteadOf "git@git.anders.fi:"
  - export PATH="$PATH:$PWD"
  - source utils/set_env_from_devops.sh
