{{- if .Values.application.migrateCommand -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "trackableappname" . }}-migrate
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "commonLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image }}"
        command: ["/bin/sh"]
        args: ["-c", "{{ .Values.application.migrateCommand }}"]
        imagePullPolicy: {{ .Values.app_image.pullPolicy }}
        {{- if .Values.application.secretName }}
        envFrom:
        - secretRef:
            name: {{ .Values.application.secretName }}
        {{- end }}
        {{- if .Values.application.fileSecretName }}
        volumeMounts:
        {{- if .Values.application.fileSecretName }}
          - mountPath: {{ .Values.application.fileSecretPath }}
            name: filesecrets
        {{- end }}
        {{- end }}
      {{- if .Values.application.fileSecretName }}
      volumes:
      {{- if .Values.application.fileSecretName }}
        - name: filesecrets
          secret:
            secretName: {{ .Values.application.fileSecretName }}
      {{- end }}
      {{- end }}
{{- end -}}
