apiVersion: v1
kind: Service
metadata:
  name: {{ template "appname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "appname" . }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ template "appname" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.service.targetPort }}
