apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "appname" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "appname" . }}
    release: {{ .Release.Name }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    # In GKE we need to specify ingress.class
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      {{- range .Values.service.urls }}
      - {{ template "hostname" . }}
      {{- end }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    {{- range .Values.service.urls }}
    - host: {{ template "hostname" . }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            backend:
              serviceName: {{ template "appname" $ }}-service
              servicePort: 80
    {{- end }}
