{{- if (not .Values.jobsOnly) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "appname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "appname" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.service.targetPort }}
{{- end }}
