apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "appname" . }}-net-policy
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          ingress: default
    - podSelector: {}
  {{- if .Values.application.monitoring.enabled }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: "{{ .Values.application.monitoring.namespace }}"
    - podSelector: {}
    ports:
    - port: {{ .Values.application.monitoring.port }}
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
