replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

app_image:
  pullPolicy: IfNotPresent

ingress:
  secretName: ai-qa-cert
  path: /
  certManagerAnnotationPrefix: cert-manager.io

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
