replicaCount: 1

service:
  url: https://localhost/
  type: ClusterIP
  port: 80
  targetPort: 8000

app_image:
  pullPolicy: Always

ingress:
  path: /
  certManagerAnnotationPrefix: cert-manager.io
  maxBodySize: 20m

application:
  track: review
  pvc:
    enabled: false
    storageClass: "standard"
    accessMode: "ReadWriteOnce"
    size: "1Gi"
  monitoring:
    enabled: false
    port: 8000
    path: "/metrics"
    namespace: "monitoring"

deployment:
  timestamp:

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
